### PR TITLE
#106 Fix handling of variable names matching reserved function names

### LINKED ISSUE #106: Formula parser does not handle name clash of variable names and special function names
###  What did you expect to happen? What did actually happen?

In a vendor provided genicam.xml for the `Point Grey/Flir Chameleon 3 CM3-U3-50S5M-CS` there exist the following nodes:
```xml
<IntSwissKnife Name="ExposureCompRangeLocked_Int">
   <pVariable Name="EXP">ExposureCompLocked_Int</pVariable>
    <Formula>( EXP = 1 ) ? 0 : 1</Formula>
</IntSwissKnife>
```

The formula `"( EXP = 1 ) ? 0 : 1"` is meant to be interpreted with `EXP` being merely a variable. However, commit 902d843335b25a2df4d6ebe3dc0238de2d905e4a parses this expression failing at  line 494
https://github.com/cameleon-rs/cameleon/blob/902d843335b25a2df4d6ebe3dc0238de2d905e4a/genapi/src/formula.rs#L492-L504

because the identifier `EXP` was determined as an `UnOpKind::Exp`. 

### How to reproduce the issue?

The easiest way would be to extend 
https://github.com/cameleon-rs/cameleon/blob/902d843335b25a2df4d6ebe3dc0238de2d905e4a/genapi/src/formula.rs#L902-L915

with a new test case, deliberately causing a name clash with either of the special functions, e.g.

```rs
#[test]
    fn test_eval_with_env() {
        let env = vec![
            ("VAR1", Expr::Integer(1)),
            ("EPS", Expr::Float(f64::EPSILON)),
            ("EXP", Expr::Float(1.0)),
        ]
        .into_iter()
        .collect();

        test_eval_impl("ABS(SIN(PI / 2) - VAR1) < EPS", &env);
        test_eval_impl("ABS(LN(E) - 1) < EPS", &env);
        test_eval_impl("ABS(1. / 2. - 0.5) < EPS", &env);
        test_eval_impl("ABS(2 ** -1 - 1. / 2.) < EPS", &env);
        test_eval_impl("ABS(2 ** -1 ** 2 - 1. / 2.) < EPS", &env);
        test_eval_impl("ABS(VAR1 + 1 / 4 - 1.25) < EPS", &env);
        test_eval_impl("( EXP = 1 ) ? 1 : 0", &env);
    }
```

###  Which manufacturer's camera did you use?

Point Grey/Flir

###  What is the model name of the camera?

Chameleon 3 CM3-U3-50S5M-CS 
same issue also with: `CM3-U3-28S4M` 
also assuming many more from this vendor.

###  Which `Cameleon` version are you using?

902d843335b25a2df4d6ebe3dc0238de2d905e4a

### PR DESCRIPTION
**Pull request by apriori**
fix #106 
- [x] Check `test_all.sh` is passed.
- [x] Add `fix #{ISSUE_NUMBER}` if the corresponding issue exists.
- [x] Fill out `## Changelog` section. If the change is for only internal use, please write `None` to the section.

## Changelog
- Formula parser now supports variable names matching special function names like "EXP" now (occured for several Point Grey camera GenICam xmls)

### CODE REVIEW

File: genapi/src/formula.rs [hunk 1]
```diff
@@ -514,7 +500,35 @@ impl<'a> Parser<'a> {
             Expr::Float(f)
         } else {
             let s = self.next_ident().unwrap();
-            Expr::Ident(s)
+            if self.eat(&Token::LParen) {
+                let op = Some(match s.as_str() {
```
Comment (Y-Nak) [inline genapi/src/formula.rs:504]:
```suggestion
                let op = match s.as_str() {
```
`op` is no longer needed to have `Option`.

File: genapi/src/formula.rs [hunk 2]
```diff
@@ -514,7 +500,35 @@ impl<'a> Parser<'a> {
...
+                    "ABS" => UnOpKind::Abs,
+                    "EXP" => UnOpKind::Exp,
+                    "LN" => UnOpKind::Ln,
+                    "LG" => UnOpKind::Lg,
+                    "SQRT" => UnOpKind::Sqrt,
+                    "TRUNC" => UnOpKind::Trunc,
+                    "FLOOR" => UnOpKind::Floor,
+                    "CEIL" => UnOpKind::Ceil,
+                    "ROUND" => UnOpKind::Round,
+                    _ => return Expr::Ident(s),
```
Comment (Y-Nak) [inline genapi/src/formula.rs:521]:
```suggestion
                    other =>  _ => panic!("{} is not a keyword for function call", other),
```
Currently,  the parser of `cameleon-genapi` is designed to panic if input XML doesn't meet GenApi specification, though it may return `Err` in the future.

**Review by Y-Nak — COMMENTED** [review]
Cool! I left some nits.

BTW, does the `stream` example runs well on your camera?

**Comment by Y-Nak** [comment]
ping @apriori, do you have any updates on this? I can take over this PR if you want.

**Comment by apriori** [comment]
Hey @Y-Nak. I'm terribly sorry for the delay. I won't be able to get to this before tomorrow.

**Comment by Y-Nak** [comment]
Thanks, @apriori.
No need to say sorry, we really appreciate your contribution!

File: genapi/src/formula.rs (hunk 1 above)
Comment (apriori) [reply genapi/src/formula.rs]: Adressed in f419ab06344ba59663868abac1c3ad53c3879ef2

File: genapi/src/formula.rs (hunk 2 above)
Comment (apriori) [reply genapi/src/formula.rs]: Adressed in f419ab06344ba59663868abac1c3ad53c3879ef2

**Comment by Y-Nak** [comment]
Almost all look good!
CI is failed due to formatting, you could fix this by running `cargo fmt --all`.

**Comment by Y-Nak** [comment]
@apriori Thank you so much! (CI is still failed but this is not your fault, this is because of the false-positive of `clippy::default_numeric_fallback` ref: https://github.com/rust-lang/rust-clippy/issues/7445. I'll temporarily disable the lint later).
